//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class animalType
    {
        public animalType()
        {
            this.animals = new HashSet<animal>();
        }
    
        public int id { get; set; }
        public string animalType1 { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
    
        public virtual ICollection<animal> animals { get; set; }
    }
}
