//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal
    {
        public animal()
        {
            this.animalBreeds = new HashSet<animalBreed>();
        }
    
        public int id { get; set; }
        public Nullable<int> animalTypeId { get; set; }
        public string animalName { get; set; }
        public string callingName { get; set; }
        public string scientificName { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
    
        public virtual animalType animalType { get; set; }
        public virtual ICollection<animalBreed> animalBreeds { get; set; }
    }
}
