//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinicSubscription
    {
        public clinicSubscription()
        {
            this.clinicSubscriptionStatus = new HashSet<clinicSubscriptionStatu>();
            this.clinicSubscriptionAddons = new HashSet<clinicSubscriptionAddon>();
        }
    
        public long id { get; set; }
        public Nullable<int> clinicId { get; set; }
        public Nullable<int> paymentSchemeId { get; set; }
        public Nullable<System.DateTime> subscribedFrom { get; set; }
        public Nullable<System.DateTime> subscribedTo { get; set; }
        public Nullable<int> subscribedUnits { get; set; }
        public Nullable<long> schemeAllowedTransactions { get; set; }
        public Nullable<System.DateTime> subscribedDate { get; set; }
        public Nullable<decimal> schemeFee { get; set; }
        public Nullable<bool> isCurrent { get; set; }
        public Nullable<bool> isRedeemed { get; set; }
    
        public virtual clinic clinic { get; set; }
        public virtual ICollection<clinicSubscriptionStatu> clinicSubscriptionStatus { get; set; }
        public virtual paymentScheme paymentScheme { get; set; }
        public virtual ICollection<clinicSubscriptionAddon> clinicSubscriptionAddons { get; set; }
    }
}
