//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinic
    {
        public clinic()
        {
            this.clinicServiceHours = new HashSet<clinicServiceHour>();
            this.clinicServiceTypes = new HashSet<clinicServiceType>();
            this.clinicSubscriptionStatus = new HashSet<clinicSubscriptionStatu>();
            this.clinicSubscriptions = new HashSet<clinicSubscription>();
            this.webUsers = new HashSet<webUser>();
        }
    
        public int id { get; set; }
        public Nullable<int> clinicTypeId { get; set; }
        public string clinicName { get; set; }
        public string slogan { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public Nullable<int> cityId { get; set; }
        public System.Data.Entity.Spatial.DbGeometry gps { get; set; }
        public string telephoneNumber { get; set; }
        public string mobileNumber { get; set; }
        public string email { get; set; }
        public string logo { get; set; }
        public Nullable<bool> isOpen { get; set; }
        public Nullable<int> transactionCount { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public string lastUpdatedBy { get; set; }
    
        public virtual clinicType clinicType { get; set; }
        public virtual ICollection<clinicServiceHour> clinicServiceHours { get; set; }
        public virtual ICollection<clinicServiceType> clinicServiceTypes { get; set; }
        public virtual ICollection<clinicSubscriptionStatu> clinicSubscriptionStatus { get; set; }
        public virtual ICollection<clinicSubscription> clinicSubscriptions { get; set; }
        public virtual ICollection<webUser> webUsers { get; set; }
    }
}
