//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinicServiceType
    {
        public clinicServiceType()
        {
            this.clinicServiceRequests = new HashSet<clinicServiceRequest>();
        }
    
        public int id { get; set; }
        public Nullable<int> clinicId { get; set; }
        public Nullable<int> serviceTypeId { get; set; }
    
        public virtual clinic clinic { get; set; }
        public virtual ICollection<clinicServiceRequest> clinicServiceRequests { get; set; }
        public virtual serviceType serviceType { get; set; }
    }
}
