//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinicServiceRequest
    {
        public long id { get; set; }
        public Nullable<long> requestedTimeSlotId { get; set; }
        public Nullable<long> petOwnerId { get; set; }
        public Nullable<int> clinicServiceTypeId { get; set; }
        public string requestRemark { get; set; }
        public Nullable<System.DateTime> requestedTime { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<bool> isCompleted { get; set; }
        public Nullable<System.DateTime> completedTime { get; set; }
        public Nullable<bool> isRescheduled { get; set; }
        public Nullable<long> selfReference { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual clinicServiceType clinicServiceType { get; set; }
        public virtual petOwner petOwner { get; set; }
        public virtual vetClinicScheduleSlot vetClinicScheduleSlot { get; set; }
    }
}
