//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinicType
    {
        public clinicType()
        {
            this.clinics = new HashSet<clinic>();
            this.paymentSchemes = new HashSet<paymentScheme>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<clinic> clinics { get; set; }
        public virtual ICollection<paymentScheme> paymentSchemes { get; set; }
    }
}
