//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinicServiceHour
    {
        public int id { get; set; }
        public Nullable<int> clinicId { get; set; }
        public string day { get; set; }
        public Nullable<System.TimeSpan> openingTime { get; set; }
        public Nullable<System.TimeSpan> closingTime { get; set; }
    
        public virtual clinic clinic { get; set; }
    }
}
