//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ioLogger
    {
        public long id { get; set; }
        public Nullable<System.DateTime> triggeredTime { get; set; }
        public string json { get; set; }
        public string url { get; set; }
        public string type { get; set; }
        public string headers { get; set; }
        public string userName { get; set; }
    }
}
