//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentScheme
    {
        public paymentScheme()
        {
            this.clinicSubscriptions = new HashSet<clinicSubscription>();
        }
    
        public int id { get; set; }
        public Nullable<int> clinicTypeId { get; set; }
        public Nullable<int> paymentPlanTypeId { get; set; }
        public string schemeName { get; set; }
        public Nullable<long> allowedTransactions { get; set; }
        public Nullable<decimal> schemeFee { get; set; }
        public Nullable<bool> isFree { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<clinicSubscription> clinicSubscriptions { get; set; }
        public virtual clinicType clinicType { get; set; }
        public virtual paymentPlanType paymentPlanType { get; set; }
    }
}
