//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class petOwner
    {
        public petOwner()
        {
            this.clinicServiceRequests = new HashSet<clinicServiceRequest>();
        }
    
        public long id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<long> petId { get; set; }
        public Nullable<bool> isMainOwner { get; set; }
        public Nullable<int> sharedUserId { get; set; }
        public Nullable<System.DateTime> sharedTime { get; set; }
        public Nullable<System.DateTime> acceptedTime { get; set; }
        public Nullable<System.DateTime> enteryDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<clinicServiceRequest> clinicServiceRequests { get; set; }
        public virtual pet pet { get; set; }
        public virtual user user { get; set; }
    }
}
