//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class petVetClinic
    {
        public long id { get; set; }
        public Nullable<long> petId { get; set; }
        public Nullable<int> vetClinicId { get; set; }
    
        public virtual pet pet { get; set; }
        public virtual vetClinic vetClinic { get; set; }
    }
}
