//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetWhizzEntities : DbContext
    {
        public PetWhizzEntities()
            : base("name=PetWhizzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<animal> animals { get; set; }
        public virtual DbSet<animalBreed> animalBreeds { get; set; }
        public virtual DbSet<animalType> animalTypes { get; set; }
        public virtual DbSet<clinic> clinics { get; set; }
        public virtual DbSet<clinicServiceHour> clinicServiceHours { get; set; }
        public virtual DbSet<clinicServiceRequest> clinicServiceRequests { get; set; }
        public virtual DbSet<clinicServiceType> clinicServiceTypes { get; set; }
        public virtual DbSet<clinicSubscription> clinicSubscriptions { get; set; }
        public virtual DbSet<clinicSubscriptionAddon> clinicSubscriptionAddons { get; set; }
        public virtual DbSet<clinicSubscriptionStatu> clinicSubscriptionStatus { get; set; }
        public virtual DbSet<clinicType> clinicTypes { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<ioLogger> ioLoggers { get; set; }
        public virtual DbSet<paymentPlanType> paymentPlanTypes { get; set; }
        public virtual DbSet<paymentScheme> paymentSchemes { get; set; }
        public virtual DbSet<pet> pets { get; set; }
        public virtual DbSet<petOwner> petOwners { get; set; }
        public virtual DbSet<petVetClinic> petVetClinics { get; set; }
        public virtual DbSet<serviceType> serviceTypes { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userDevice> userDevices { get; set; }
        public virtual DbSet<userToken> userTokens { get; set; }
        public virtual DbSet<userVerification> userVerifications { get; set; }
        public virtual DbSet<vet> vets { get; set; }
        public virtual DbSet<vetClinic> vetClinics { get; set; }
        public virtual DbSet<vetClinicSchedule> vetClinicSchedules { get; set; }
        public virtual DbSet<vetClinicScheduleSlot> vetClinicScheduleSlots { get; set; }
        public virtual DbSet<vetType> vetTypes { get; set; }
        public virtual DbSet<webUser> webUsers { get; set; }
        public virtual DbSet<webUserType> webUserTypes { get; set; }
    }
}
