//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.petOwners = new HashSet<petOwner>();
            this.userDevices = new HashSet<userDevice>();
            this.userVerifications = new HashSet<userVerification>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string eMail { get; set; }
        public string mobileNumber { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public Nullable<int> stateId { get; set; }
        public string postalCode { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string profilePic { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
    
        public virtual ICollection<petOwner> petOwners { get; set; }
        public virtual state state { get; set; }
        public virtual ICollection<userDevice> userDevices { get; set; }
        public virtual ICollection<userVerification> userVerifications { get; set; }
    }
}
