//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class userVerification
    {
        public long id { get; set; }
        public int userId { get; set; }
        public string verificationType { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> generatedTime { get; set; }
        public Nullable<System.DateTime> expiryTime { get; set; }
        public Nullable<bool> isValid { get; set; }
    
        public virtual user user { get; set; }
    }
}
