//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class userToken
    {
        public long id { get; set; }
        public long userDeviceId { get; set; }
        public string tokenType { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> generatedTime { get; set; }
        public Nullable<System.DateTime> expiryTime { get; set; }
        public Nullable<int> useCount { get; set; }
    
        public virtual userDevice userDevice { get; set; }
    }
}
