//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vet
    {
        public vet()
        {
            this.webUsers = new HashSet<webUser>();
        }
    
        public int id { get; set; }
        public Nullable<int> vetTypeId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string regNo { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string profilePicture { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual vetType vetType { get; set; }
        public virtual ICollection<webUser> webUsers { get; set; }
    }
}
