//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vetClinicSchedule
    {
        public vetClinicSchedule()
        {
            this.vetClinicScheduleSlots = new HashSet<vetClinicScheduleSlot>();
        }
    
        public long id { get; set; }
        public Nullable<int> vetClinicId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual vetClinic vetClinic { get; set; }
        public virtual ICollection<vetClinicScheduleSlot> vetClinicScheduleSlots { get; set; }
    }
}
