//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vetClinic
    {
        public vetClinic()
        {
            this.petVetClinics = new HashSet<petVetClinic>();
            this.vetClinicSchedules = new HashSet<vetClinicSchedule>();
        }
    
        public int id { get; set; }
        public Nullable<int> vetId { get; set; }
        public Nullable<int> clinicId { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<petVetClinic> petVetClinics { get; set; }
        public virtual ICollection<vetClinicSchedule> vetClinicSchedules { get; set; }
    }
}
