//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWhizz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class webUser
    {
        public long id { get; set; }
        public Nullable<int> webUserTypeId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> vetId { get; set; }
        public Nullable<int> clinicId { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual clinic clinic { get; set; }
        public virtual vet vet { get; set; }
        public virtual webUserType webUserType { get; set; }
    }
}
